### ISSUE TITLE
Old world waypoint still showing up

### ISSUE THREAD

**Issue by mattiaperry95** [TeamJM/journeymap-webmap#5]
Hi, I installed Journeymap, created a new world, fucked around a bit, didnt like the worldgen, created a new one. Now when opening the map i still have the old world map, with the current new world map overwriting it as i go around. the problem got solved just by clicking an delete all dimension maps. but another arises, this time with this addon. in the old world i made various waypoints and now when i open the new world map in journeymap webmap those waypoints are still there. Ill upload a screenshot:
![Screenshot 2024-09-25 135931](https://github.com/user-attachments/assets/79321f59-21ed-4ee9-852e-79ff669bb084)

**Comment by mysticdrew** [comment]
yea, you need to delete them. 
when you create a world "Minecraft World" or what ever the default name is. Then delete, create a new world with the exact same name. JourneyMap has no idea it is a new world. Because minecraft saves it in the same directory name, which is what we use to identify singleplayer worlds.
